export default {
  access: [
    { label: 'DIRECT WITH AGENT', value: 'Direct With Agent' },
    { label: 'MEETING CLIENT', value: 'Meeting Client' },
    { label: 'KEY COLLECTION', value: 'Key Collection' },
  ],
  product: [
    { label: 'PHOTOGRAPHY', value: 'Photography' },
    { label: 'FLOOR PLAN', value: 'Floor Plan' },
    { label: 'EPC', value: 'EPC' },
  ],
  photographerToBeTaken: [
    { label: 'PHOTOGRAPHERS CHOICE', value: 0 },
    { label: 'SPECIFIC PHOTOGRAPHS', value: 1 },
  ],
  specificPhotographers: [
    'FRONT (PORTRAIT)',
    'FRONT (ANGLED)',
    'FRONT (STRAIGHT)',
    `BACK`,
    'BACK (PORTRAIT)',
    'GARDEN 1',
    'GARDEN 2',
    'GARDEN (TOWARDS)',
    'ENTRANCE',
    'VESTIBULE',
    'HALLWAY',
    'LANDING',
    'RECEPTION ROOM 1',
    'RECEPTION ROOM 2',
    'DINING ROOM/AREA',
    'KITCHEN 1',
    'KITCHEN 2',
    'CONSERVATORY',
    'GARAGE/PARKING',
    'OUTBUILDING/<br/>SUMMERHOUSE',
    'BEDROOM 1',
    'BEDROOM 2',
    'BEDROOM 3',
    'BEDROOM 4',
    'ENSUITE',
    'BATHROOM 1',
    'BATHROOM 2',
    'SHOWER ROOM',
    'SWIMMING POOL',
    'SAUNA',
    'VIEW',
    'BALCONY',
    'GYM',
    'CONCIERGE',
    'SURROUNDING<br/>AREA 1',
    'SURROUNDING<br/>AREA 2',
    'OTHER 1<br/>(SEE NOTES)',
    'OTHER 2<br/>(SEE NOTES)',
    'OTHER 3<br/>(SEE NOTES)',
    'OTHER 4<br/>(SEE NOTES)',
  ],
  bedrooms: [
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
  ],
  furnishing: [{ label: 'Furnished', value: 1 }, { label: 'Unfurnished', value: 0 }],
  property: [
    { label: 'House', value: 'House' },
    { label: 'Maisonette', value: 'Maisonette' },
    { label: 'Flat', value: 'Flat' },
  ],
};
